name: foodnbod
description: "AI health and fitness assistant."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.20.1
  http: ^1.3.0
  pedometer: ^4.0.1
  permission_handler: ^11.3.1
  percent_indicator: ^4.2.3
  table_calendar: ^3.1.2
  mobile_scanner: ^6.0.0
  shared_preferences: ^2.3.5
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
