name: foodnbod
description: "AI health and fitness assistant."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  intl: ^0.19.0
  http: ^1.1.0
  pedometer: ^4.0.1
  permission_handler: ^11.3.1
  percent_indicator: ^4.2.3
  table_calendar: ^3.1.0
  mobile_scanner: ^3.5.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
